development: &default
  adapter: postgresql
  database: raystask_development
  encoding: utf8
  min_messages: warning
  pool: 5
  timeout: 5000

test:
  <<: *default
  database: raystask_test

production:
  <<: *default

