default: &default
  adapter: postgresql
  encoding: unicode

development: &default
  adapter: postgresql
  database: raystask_development
  encoding: utf8
  min_messages: warning
  pool: 5
  timeout: 5000

test:
  database: raystask_test

production: &default
